### ISSUE TITLE
Add ability to limit block scope similar to what's done in dipdup

### ISSUE THREAD

**Issue by kindsun** [dipdup-io/metadata#20]
In dipdup, it's currently possible to limit the block scope via config using the following settings:
```
indexes:
  my_index:
    first_level: 1000000
    last_level: 2000000
```
For testing, it would be useful to be able to do the same thing in the metadata plugin. This would also limit the tester's S3 footprint which is nice for cost savings!
